version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: rgd
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioAdminAccessKey
      MINIO_SECRET_KEY: minioAdminSecretKey
    volumes:
      - /data
