---
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:latest-postgis-ram
        environment:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
      - image: minio/minio:latest
        command: server /data
        environment:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install tox and codecov
          command: sudo pip install tox codecov
      - run:
          name: Debugging
          command: which docker;docker --help
      - run:
          name: Run tests
          command: tox
          environment:
            DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
            DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
            DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
            DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
            DOCKER_CMD: /usr/bin/docker
            DOCKER_SOCK: $DOCKER_HOST/var/run/docker.sock
      - run:
          name: Upload Coverage
          command: codecov
workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
